name: deepdfa
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.12
  - pytorch::pytorch==2.3.1
  - pytorch-cuda=12.1
  - pytorch::torchvision==0.18.1
  - pytorch::torchaudio==2.3.1
  # conda-forge::cudatoolkit=11.8. We need 12.1 and upwards so this comes from nvidia channel
  - nvidia/label/cuda-12.1.0::cuda # for nvcc and friends
  #- dgl # dgl doesnt support pytorch 2.4 yet, so need pytorch 2.3.1, with cuda 12.1
  - pip
  - pip:
    - pybind11
    - torch_scatter
    - torch_sparse
    - -f https://data.dgl.ai/wheels/torch-2.3/cu121/repo.html
    - dgl
    - numpy
    - pandas
    - tqdm
    - pytorch-lightning==2.4
    - torchmetrics==1.4.1
    - torchsampler
    - nni
    - silence-tensorflow
    - tensorflow
    - scipy
    - captum
    - deepspeed
    - scikit-learn
    - tokenizers
    - transformers
    - tree-sitter
    - unidiff
    - jsonlines
    - networkx
    - pexpect
    - jsonargparse[signatures]
    - fastparquet
    - gdown
    # these are dependencies of neural-subgraph-learning-GNN project
    - deepsnap
    - matplotlib
    - networkx
    - scikit-learn
    - seaborn
    - torch_geometric
    #- test_tube
    - xgboost
    #- torch
    #- torch_scatter
    #- torch_sparse
